### ISSUE TITLE
Wrong data in clipboard.

### ISSUE THREAD

**Issue by q000p** [chcg/NPP_HexEdit#55] opened 2021-08-11 10:27 UTC
If I copy to clipboard hex data as "8c 00 a4 9e 65"  I get after paste "8c 20 a4 9e 65"

**Comment by hoensr** [comment] 2021-11-02 12:03
Duplicate of #24
See also here: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9289
I don't think it will be fixed soon.

**Closed** 2021-11-02 13:08 UTC
Labels: duplicate
